language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_script:
  - npm install -g npm@latest
  - npm install -g flow
  - npm install -g eslint
  - npm install -g expo
  - npm install -g expo-cli
  - npm install
script:
  - npm run eslint
  - npm run flow
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - expo publish --non-interactive
