// flow-typed signature: fd35a28ae83c6d73ce5ab41b5a1c84d4
// flow-typed version: <<STUB>>/expo-permissions_v5.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-permissions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-permissions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-permissions/build/CoalescedPermissions' {
  declare module.exports: any;
}

declare module 'expo-permissions/build/ExpoPermissions' {
  declare module.exports: any;
}

declare module 'expo-permissions/build/ExpoPermissions.web' {
  declare module.exports: any;
}

declare module 'expo-permissions/build/Permissions' {
  declare module.exports: any;
}

declare module 'expo-permissions/build/Permissions.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-permissions/build/CoalescedPermissions.js' {
  declare module.exports: $Exports<'expo-permissions/build/CoalescedPermissions'>;
}
declare module 'expo-permissions/build/ExpoPermissions.js' {
  declare module.exports: $Exports<'expo-permissions/build/ExpoPermissions'>;
}
declare module 'expo-permissions/build/ExpoPermissions.web.js' {
  declare module.exports: $Exports<'expo-permissions/build/ExpoPermissions.web'>;
}
declare module 'expo-permissions/build/Permissions.js' {
  declare module.exports: $Exports<'expo-permissions/build/Permissions'>;
}
declare module 'expo-permissions/build/Permissions.types.js' {
  declare module.exports: $Exports<'expo-permissions/build/Permissions.types'>;
}
declare module 'expo-permissions/index' {
  declare module.exports: $Exports<'expo-permissions'>;
}
declare module 'expo-permissions/index.js' {
  declare module.exports: $Exports<'expo-permissions'>;
}
