// flow-typed signature: 46261db8f11eda5a39e58863aad223b8
// flow-typed version: <<STUB>>/expo-file-system_v5.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-file-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-file-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-file-system/build/ExponentFileSystem' {
  declare module.exports: any;
}

declare module 'expo-file-system/build/ExponentFileSystem.web' {
  declare module.exports: any;
}

declare module 'expo-file-system/build/ExponentFileSystemShim' {
  declare module.exports: any;
}

declare module 'expo-file-system/build/FileSystem' {
  declare module.exports: any;
}

declare module 'expo-file-system/build/FileSystem.types' {
  declare module.exports: any;
}

declare module 'expo-file-system/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-file-system/build/ExponentFileSystem.js' {
  declare module.exports: $Exports<'expo-file-system/build/ExponentFileSystem'>;
}
declare module 'expo-file-system/build/ExponentFileSystem.web.js' {
  declare module.exports: $Exports<'expo-file-system/build/ExponentFileSystem.web'>;
}
declare module 'expo-file-system/build/ExponentFileSystemShim.js' {
  declare module.exports: $Exports<'expo-file-system/build/ExponentFileSystemShim'>;
}
declare module 'expo-file-system/build/FileSystem.js' {
  declare module.exports: $Exports<'expo-file-system/build/FileSystem'>;
}
declare module 'expo-file-system/build/FileSystem.types.js' {
  declare module.exports: $Exports<'expo-file-system/build/FileSystem.types'>;
}
declare module 'expo-file-system/build/index.js' {
  declare module.exports: $Exports<'expo-file-system/build/index'>;
}
