// flow-typed signature: 286dd454289ddd3f709079d587ab3c05
// flow-typed version: <<STUB>>/expo-image-manipulator_v5.0.1/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-image-manipulator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-image-manipulator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-image-manipulator/build/ExpoImageManipulator' {
  declare module.exports: any;
}

declare module 'expo-image-manipulator/build/ExpoImageManipulator.web' {
  declare module.exports: any;
}

declare module 'expo-image-manipulator/build/ImageManipulator' {
  declare module.exports: any;
}

declare module 'expo-image-manipulator/build/ImageManipulator.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-image-manipulator/build/ExpoImageManipulator.js' {
  declare module.exports: $Exports<'expo-image-manipulator/build/ExpoImageManipulator'>;
}
declare module 'expo-image-manipulator/build/ExpoImageManipulator.web.js' {
  declare module.exports: $Exports<'expo-image-manipulator/build/ExpoImageManipulator.web'>;
}
declare module 'expo-image-manipulator/build/ImageManipulator.js' {
  declare module.exports: $Exports<'expo-image-manipulator/build/ImageManipulator'>;
}
declare module 'expo-image-manipulator/build/ImageManipulator.types.js' {
  declare module.exports: $Exports<'expo-image-manipulator/build/ImageManipulator.types'>;
}
