// flow-typed signature: 8e1b0781132df00aa8f2ec2707faebf2
// flow-typed version: <<STUB>>/react-router-native_v4.3.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-native/BackButton' {
  declare module.exports: any;
}

declare module 'react-router-native/DeepLinking' {
  declare module.exports: any;
}

declare module 'react-router-native/experimental/StackRoute' {
  declare module.exports: any;
}

declare module 'react-router-native/experimental/TabRoutes' {
  declare module.exports: any;
}

declare module 'react-router-native/Link' {
  declare module.exports: any;
}

declare module 'react-router-native/main' {
  declare module.exports: any;
}

declare module 'react-router-native/NativeRouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-native/BackButton.js' {
  declare module.exports: $Exports<'react-router-native/BackButton'>;
}
declare module 'react-router-native/DeepLinking.js' {
  declare module.exports: $Exports<'react-router-native/DeepLinking'>;
}
declare module 'react-router-native/experimental/StackRoute.js' {
  declare module.exports: $Exports<'react-router-native/experimental/StackRoute'>;
}
declare module 'react-router-native/experimental/TabRoutes.js' {
  declare module.exports: $Exports<'react-router-native/experimental/TabRoutes'>;
}
declare module 'react-router-native/Link.js' {
  declare module.exports: $Exports<'react-router-native/Link'>;
}
declare module 'react-router-native/main.js' {
  declare module.exports: $Exports<'react-router-native/main'>;
}
declare module 'react-router-native/NativeRouter.js' {
  declare module.exports: $Exports<'react-router-native/NativeRouter'>;
}
