// flow-typed signature: d153be5f408069ed6d4222a4a647a5d5
// flow-typed version: <<STUB>>/react-native-root-toast_v3.0.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-root-toast'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-root-toast' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-root-toast/Example/Field' {
  declare module.exports: any;
}

declare module 'react-native-root-toast/Example/index.android' {
  declare module.exports: any;
}

declare module 'react-native-root-toast/Example/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-root-toast/Example/main' {
  declare module.exports: any;
}

declare module 'react-native-root-toast/lib/Toast' {
  declare module.exports: any;
}

declare module 'react-native-root-toast/lib/ToastContainer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-root-toast/Example/Field.js' {
  declare module.exports: $Exports<'react-native-root-toast/Example/Field'>;
}
declare module 'react-native-root-toast/Example/index.android.js' {
  declare module.exports: $Exports<'react-native-root-toast/Example/index.android'>;
}
declare module 'react-native-root-toast/Example/index.ios.js' {
  declare module.exports: $Exports<'react-native-root-toast/Example/index.ios'>;
}
declare module 'react-native-root-toast/Example/main.js' {
  declare module.exports: $Exports<'react-native-root-toast/Example/main'>;
}
declare module 'react-native-root-toast/index' {
  declare module.exports: $Exports<'react-native-root-toast'>;
}
declare module 'react-native-root-toast/index.js' {
  declare module.exports: $Exports<'react-native-root-toast'>;
}
declare module 'react-native-root-toast/lib/Toast.js' {
  declare module.exports: $Exports<'react-native-root-toast/lib/Toast'>;
}
declare module 'react-native-root-toast/lib/ToastContainer.js' {
  declare module.exports: $Exports<'react-native-root-toast/lib/ToastContainer'>;
}
