// flow-typed signature: c86456590b7e8d5fd815fb01ac708946
// flow-typed version: <<STUB>>/react-native-modal-dropdown_v0.6.2/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-modal-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-modal-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-modal-dropdown/components/ModalDropdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-modal-dropdown/components/ModalDropdown.js' {
  declare module.exports: $Exports<'react-native-modal-dropdown/components/ModalDropdown'>;
}
declare module 'react-native-modal-dropdown/index' {
  declare module.exports: $Exports<'react-native-modal-dropdown'>;
}
declare module 'react-native-modal-dropdown/index.js' {
  declare module.exports: $Exports<'react-native-modal-dropdown'>;
}
